
package ai_project2;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;


class PolyLine{

    public int x[];
    public int y[];
    public int Type_Of_Class;
    
    public PolyLine(int x[],int y[],int Type_Of_Class){
       this.x=x;
       this.y=y;
       this.Type_Of_Class = Type_Of_Class;
}
}


public class panel extends javax.swing.JPanel {

    public panel() {
        initComponents();
    }

    
    
    private ArrayList<PolyLine> graphPolyLines=new ArrayList<PolyLine>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);     
        g.setColor(Color.blue);
        g.drawLine(0, this.getHeight()/2, this.getWidth(), this.getHeight()/2);
        g.drawLine(this.getWidth()/2, 0, this.getWidth()/2, this.getHeight());
       
        drawGraphPolyLines(g);
    }

     private void drawGraphPolyLines(Graphics drawingTool){
        
        for(PolyLine p : graphPolyLines){
            if(p.Type_Of_Class == 1){
                drawingTool.setColor(Color.black);
            }
            else if (p.Type_Of_Class == 2){
                drawingTool.setColor(Color.orange);
            }
            else if (p.Type_Of_Class == 3){
                drawingTool.setColor(Color.red); 
            }
            else if (p.Type_Of_Class == 4){
                drawingTool.setColor(Color.PINK);
            }
               
           
            drawingTool.drawLine(p.x[0],p.x[1], p.y[0], p.y[1]);
        } 
    }


    public void drawPolyLine(int x[],int y[],int Type_Of_Class){   
        graphPolyLines.add(new PolyLine(x, y , Type_Of_Class));
        repaint();
    }
    
    public void clearGraph(){
        graphPolyLines=new ArrayList<PolyLine>();
        System.gc();
        repaint();
    }
        
    
        
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
